version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.10.cli-migrations
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes:
    - ./hasura/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
    env_file:
      - .env
volumes:
  db_data:
